# Generated by Django 4.2.3 on 2023-07-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('donation_option', models.CharField(choices=[('cash', 'In Cash'), ('kind', 'In Kind')], max_length=10)),
                ('applied_date', models.DateField()),
                ('contacted', models.BooleanField(default=False)),
            ],
        ),
    ]
