# Generated by Django 4.2.3 on 2023-07-24 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='applied_date',
        ),
        migrations.AddField(
            model_name='donation',
            name='created_date',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
