# Generated by Django 4.2.3 on 2023-07-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('dateOfBirth', models.DateField()),
                ('region', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('wereda', models.CharField(max_length=255)),
                ('parentFirstName', models.CharField(max_length=255)),
                ('parentLastName', models.CharField(max_length=255)),
                ('parentEmail', models.EmailField(max_length=254)),
                ('parentPhoneNumber', models.CharField(max_length=20)),
                ('schoolName', models.CharField(max_length=255)),
                ('schoolType', models.CharField(max_length=255)),
                ('schoolRegion', models.CharField(max_length=255)),
                ('schoolZone', models.CharField(max_length=255)),
                ('schoolWereda', models.CharField(max_length=255)),
                ('educationalLevel', models.CharField(max_length=255)),
                ('documentLink', models.URLField()),
                ('projectDetail', models.TextField()),
                ('selectedReadingRating', models.CharField(max_length=10)),
                ('selectedWritingRating', models.CharField(max_length=10)),
                ('selectedListenRating', models.CharField(max_length=10)),
                ('selectedSpeakingRating', models.CharField(max_length=10)),
                ('motivationDetail', models.TextField()),
                ('cvLink', models.URLField()),
                ('certificateLink', models.URLField()),
                ('recommendationLink', models.URLField()),
                ('skillOption', models.CharField(max_length=255)),
                ('competition', models.CharField(max_length=255)),
                ('participation', models.CharField(max_length=255)),
                ('projectOption', models.CharField(max_length=255)),
                ('competitionOption', models.CharField(max_length=255)),
                ('selectedRating', models.CharField(max_length=10)),
                ('languages', models.ManyToManyField(related_name='applicants', to='user.language')),
                ('orgs', models.ManyToManyField(to='user.organization')),
                ('selectedpLanguages', models.ManyToManyField(to='user.language')),
                ('skills', models.ManyToManyField(to='user.skill')),
            ],
        ),
    ]
