# Generated by Django 4.2.3 on 2023-07-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_applicant_certificatelink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='educationalLevel',
            field=models.CharField(blank=True, choices=[('1', 'Beginner'), ('2', 'Beginner'), ('3', 'Beginner'), ('4', 'Beginner'), ('5', 'Beginner'), ('6', 'Beginner'), ('7', 'Beginner'), ('8', 'Beginner'), ('9', 'Intermediate'), ('10', 'Intermediate'), ('11', 'Advanced'), ('12', 'Advanced')], default='1', max_length=255),
        ),
    ]
